enableGlobalCache: true
enableTelemetry: false
nmHoistingLimits: workspaces
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
preferAggregateCacheInfo: true
yarnPath: .yarn/releases/yarn-3.0.1.cjs
nmMode: hardlinks-local
logFilters:
  - level: discard
    code: YN0002
  - level: discard
    code: YN0062
