# nonk8s
apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: cms
      docker:
        target: cms
    - image: website
      docker:
        target: website
  local:
    useDockerCLI: true
    useBuildkit: true
profiles:
  - name: production
    build:
      tagPolicy:
        gitCommit:
          variant: Tags
          ignoreChanges: true
